/*
    CELLAR_LVL2_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_CELLAR_LVL2_TILES_H__
#define __MAP_CELLAR_LVL2_TILES_H__

#define CELLAR_LVL2_TILE_COUNT 24

extern const void __bank_CELLAR_LVL2_TILE_DATA;

extern const unsigned char CELLAR_LVL2_TILE_DATA[];

#endif
