/*
    CELLAR_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_CELLAR_MAP_H__
#define __MAP_CELLAR_MAP_H__

#define CELLAR_MAP_WIDTH 20
#define CELLAR_MAP_HEIGHT 18

extern const void __bank_CELLAR_MAP_DATA;

extern const unsigned char CELLAR_MAP_DATA[];

#endif
