/*
    CELLAR_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_CELLAR_TILES_H__
#define __MAP_CELLAR_TILES_H__

#define CELLAR_TILE_COUNT 28

extern const void __bank_CELLAR_TILE_DATA;

extern const unsigned char CELLAR_TILE_DATA[];

#endif
