/*
    CELLAR_TILES.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_CELLAR_TILES_H__
#define __MAP_CELLAR_TILES_H__

#define CELLAR_TILE_COUNT 28

extern const unsigned char CELLAR_TILE_DATA[];

#endif
