/*
    CELLAR_MAP.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_CELLAR_MAP_H__
#define __MAP_CELLAR_MAP_H__

#define CELLAR_MAP_WIDTH 20
#define CELLAR_MAP_HEIGHT 18

extern const unsigned char CELLAR_MAP_DATA[];

#endif
