/*
    BKG_SUBMAP_TILES.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_BKG_SUBMAP_TILES_H__
#define __MAP_BKG_SUBMAP_TILES_H__

#define BKG_SUBMAP_TILE_COUNT 213

extern const unsigned char BKG_SUBMAP_TILE_DATA[];

#endif
