/*
    SUBMAP_TILES.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_SUBMAP_TILES_H__
#define __MAP_SUBMAP_TILES_H__

#define SUBMAP_TILE_COUNT 213

extern const unsigned char SUBMAP_TILE_DATA[];

#endif
