/*
    SUBMAP_MAP.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_SUBMAP_MAP_H__
#define __MAP_SUBMAP_MAP_H__

#define SUBMAP_MAP_WIDTH 60
#define SUBMAP_MAP_HEIGHT 54

extern const unsigned char SUBMAP_MAP_DATA[];

#endif
