/*
    SUBMAP_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_SUBMAP_MAP_H__
#define __MAP_SUBMAP_MAP_H__

#define SUBMAP_MAP_WIDTH 60
#define SUBMAP_MAP_HEIGHT 54

extern const void __bank_SUBMAP_MAP_DATA;

extern const unsigned char SUBMAP_MAP_DATA[];

#endif
