/*
    HOUSE_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_HOUSE_TILES_H__
#define __MAP_HOUSE_TILES_H__

#define HOUSE_TILE_COUNT 65

extern const void __bank_HOUSE_TILE_DATA;

extern const unsigned char HOUSE_TILE_DATA[];

#endif
