/*
    HOUSE_MAP.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_HOUSE_MAP_H__
#define __MAP_HOUSE_MAP_H__

#define HOUSE_MAP_WIDTH 32
#define HOUSE_MAP_HEIGHT 32

extern const unsigned char HOUSE_MAP_DATA[];

#endif
